import jsPDF from 'jspdf';
import autoTable, { UserOptions } from 'jspdf-autotable';
import {
  SalesOrder,
  JobCard,
  Estimate,
  Transaction,
  SystemSettings
} from '../types';
import { formatCurrency } from './formatters';

// Helper for formatting currency inside PDFs
const formatAmount = (num: number, currency: string = 'OMR'): string => {
  return `${num.toFixed(3)} ${currency}`;
};

// Helper for drawing clean header bar
const drawPdfHeader = (
  doc: jsPDF,
  title: string,
  subtitle: string,
  docNumber?: string,
  settings?: Partial<SystemSettings>
) => {
  const companyName = settings?.companyName || 'ZUKAIT INTERNATIONAL LLC - WORKSHOP & BODYSHOP';
  const currency = settings?.currency || 'OMR';
  const vatNumber = settings?.vatNumber || 'OM-VAT-9884210';
  const crNumber = settings?.crNumber || 'CR-1049281';
  const address = settings?.address || 'Industrial Area, Muscat, Sultanate of Oman';
  const phone = settings?.phone || '+968 2450 1100';
  const email = settings?.email || 'service@zukait.om';

  // Primary top accent line
  doc.setFillColor(67, 56, 202); // Indigo 700
  doc.rect(0, 0, 210, 5, 'F');

  // Company Branding
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42); // Slate 900
  doc.text(companyName.toUpperCase(), 14, 18);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139); // Slate 500
  doc.text(`${address} • Tel: ${phone} • Email: ${email}`, 14, 23);
  doc.text(`CR: ${crNumber} • Tax/VAT Registration: ${vatNumber}`, 14, 27);

  // Document Title & Reference
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(67, 56, 202);
  doc.text(title.toUpperCase(), 196, 18, { align: 'right' });

  if (docNumber) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    doc.text(docNumber, 196, 23, { align: 'right' });
  }

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(subtitle, 196, 27, { align: 'right' });

  // Divider rule
  doc.setDrawColor(226, 232, 240); // Slate 200
  doc.setLineWidth(0.5);
  doc.line(14, 31, 196, 31);
};

// Helper for drawing standard footer on all pages
const drawPdfFooter = (doc: jsPDF) => {
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.5);
    doc.line(14, 282, 196, 282);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184); // Slate 400
    doc.text(
      `Generated by Zukait International LLC Workshop Suite • Certified Tax Compliant`,
      14,
      287
    );
    doc.text(`Page ${i} of ${pageCount}`, 196, 287, { align: 'right' });
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// 1. SALES TAX INVOICE PDF EXPORTER
// ─────────────────────────────────────────────────────────────────────────────
export const exportSalesInvoicePDF = (
  order: SalesOrder,
  settings?: Partial<SystemSettings>
) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const currency = settings?.currency || 'OMR';

  // Draw Header
  drawPdfHeader(
    doc,
    'TAX INVOICE',
    `Date: ${order.date}`,
    order.orderNumber,
    settings
  );

  // Billing & Customer Info Cards
  doc.setFillColor(248, 250, 252); // Slate 50
  doc.roundedRect(14, 35, 88, 28, 2, 2, 'F');
  doc.roundedRect(108, 35, 88, 28, 2, 2, 'F');

  // Customer Box
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text('BILLED TO (CUSTOMER):', 18, 41);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);
  doc.setTextColor(15, 23, 42);
  doc.text(order.customerName || 'General Customer', 18, 47);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(order.customerCompany || 'Private Individual', 18, 52);
  doc.text(`Account ID: ${order.customerId || 'CUST-001'}`, 18, 57);

  // Invoice Details Box
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text('INVOICE PARAMETERS:', 112, 41);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(15, 23, 42);
  doc.text(`Invoice Status: ${order.status.toUpperCase()}`, 112, 47);
  doc.text(`Payment Terms: ${order.paymentStatus === 'paid' ? 'PAID IN FULL' : 'DUE ON ' + order.dueDate}`, 112, 52);
  doc.text(`Payment Status: ${order.paymentStatus.toUpperCase()}`, 112, 57);

  // Items Table
  const tableRows = (order.items || []).map((item, idx) => [
    (idx + 1).toString(),
    item.sku || `SKU-${idx + 1}`,
    item.productName || 'Line Item',
    item.quantity.toString(),
    formatAmount(item.unitPrice, currency),
    formatAmount(item.total, currency),
  ]);

  autoTable(doc, {
    startY: 68,
    head: [['#', 'SKU / Part Code', 'Description', 'Qty', 'Unit Price', 'Amount']],
    body: tableRows,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 41, 59], // Slate 800
      textColor: [255, 255, 255],
      fontSize: 8.5,
      fontStyle: 'bold',
      halign: 'left',
    },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 32 },
      2: { cellWidth: 'auto' },
      3: { cellWidth: 16, halign: 'center' },
      4: { cellWidth: 30, halign: 'right' },
      5: { cellWidth: 30, halign: 'right' },
    },
    styles: {
      fontSize: 8,
      cellPadding: 2.8,
      lineColor: [226, 232, 240],
      textColor: [51, 65, 85],
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
  });

  const finalY = (doc as any).lastAutoTable.finalY || 150;

  // Financial Breakdown Box (Right Aligned)
  const summaryBoxWidth = 80;
  const summaryX = 196 - summaryBoxWidth;
  let currentY = finalY + 8;

  doc.setFillColor(248, 250, 252);
  doc.roundedRect(summaryX, currentY, summaryBoxWidth, 38, 2, 2, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(summaryX, currentY, summaryBoxWidth, 38, 2, 2, 'S');

  // Subtotal
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(71, 85, 105);
  doc.text('Subtotal:', summaryX + 4, currentY + 7);
  doc.text(formatAmount(order.subtotal, currency), 192, currentY + 7, { align: 'right' });

  // VAT (5%)
  doc.text('VAT / Tax (5%):', summaryX + 4, currentY + 14);
  doc.text(formatAmount(order.tax, currency), 192, currentY + 14, { align: 'right' });

  // Discount (if any)
  if (order.discount && order.discount > 0) {
    doc.text('Discount:', summaryX + 4, currentY + 21);
    doc.text(`-${formatAmount(order.discount, currency)}`, 192, currentY + 21, { align: 'right' });
  }

  // Grand Total Banner
  doc.setFillColor(67, 56, 202);
  doc.roundedRect(summaryX + 2, currentY + 25, summaryBoxWidth - 4, 10, 1.5, 1.5, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);
  doc.setTextColor(255, 255, 255);
  doc.text('TOTAL AMOUNT:', summaryX + 5, currentY + 31.5);
  doc.text(formatAmount(order.total, currency), 191, currentY + 31.5, { align: 'right' });

  // Notes and Bank Payment Details (Left Aligned)
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(15, 23, 42);
  doc.text('PAYMENT INSTRUCTIONS & WIRE TRANSFER:', 14, finalY + 10);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text('Bank Name: Bank Muscat (Corporate Banking)', 14, finalY + 16);
  doc.text('Account Name: Apex Auto Workshop & Systems LLC', 14, finalY + 20);
  doc.text('IBAN: OM44 0021 0039 4920 1928 01', 14, finalY + 24);
  doc.text('Swift/BIC: BMACOMXX', 14, finalY + 28);
  doc.text('Please include invoice number in wire reference transfer.', 14, finalY + 32);

  if (order.notes) {
    doc.setFont('helvetica', 'italic');
    doc.text(`Notes: ${order.notes}`, 14, finalY + 38);
  }

  // Draw Footer
  drawPdfFooter(doc);

  // Download
  doc.save(`Sales_Invoice_${order.orderNumber}.pdf`);
};

// ─────────────────────────────────────────────────────────────────────────────
// 2. WORKSHOP JOB CARD PROFIT & LOSS REPORT PDF EXPORTER
// ─────────────────────────────────────────────────────────────────────────────
export interface JobCardPnlBreakdown {
  partsCost: number;
  partsRevenue: number;
  laborCost: number;
  laborRevenue: number;
  consumablesCost: number;
  totalJobCost: number;
  totalRevenue: number;
  netProfit: number;
  profitMargin: number;
}

export const exportJobCardPnlReportPDF = (
  jobCards: JobCard[],
  calculatePnl: (jc: JobCard) => JobCardPnlBreakdown,
  settings?: Partial<SystemSettings>
) => {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  const currency = settings?.currency || 'OMR';
  const today = new Date().toISOString().split('T')[0];

  // Header
  drawPdfHeader(
    doc,
    'WORKSHOP P&L REPORT',
    `Generated: ${today}`,
    `JOBS: ${jobCards.length}`,
    settings
  );

  // Compute Aggregates
  const aggregates = jobCards.reduce(
    (acc, jc) => {
      const pnl = calculatePnl(jc);
      acc.totalRevenue += pnl.totalRevenue;
      acc.totalPartsCost += pnl.partsCost;
      acc.totalLaborCost += pnl.laborCost;
      acc.totalConsumablesCost += pnl.consumablesCost;
      acc.totalCost += pnl.totalJobCost;
      acc.totalProfit += pnl.netProfit;
      return acc;
    },
    {
      totalRevenue: 0,
      totalPartsCost: 0,
      totalLaborCost: 0,
      totalConsumablesCost: 0,
      totalCost: 0,
      totalProfit: 0,
    }
  );

  const overallMargin =
    aggregates.totalRevenue > 0
      ? +((aggregates.totalProfit / aggregates.totalRevenue) * 100).toFixed(1)
      : 0;

  // Executive Summary KPI Cards (Landscape)
  const kpiBoxWidth = 50;
  const kpiY = 36;
  const kpiGap = 6;
  let startX = 14;

  const kpiItems = [
    { label: 'TOTAL REVENUE', value: formatAmount(aggregates.totalRevenue, currency), color: [16, 185, 129] },
    { label: 'PARTS DIRECT COST', value: formatAmount(aggregates.totalPartsCost, currency), color: [99, 102, 241] },
    { label: 'LABOR WAGE COST', value: formatAmount(aggregates.totalLaborCost, currency), color: [245, 158, 11] },
    { label: 'CONSUMABLES / MAT', value: formatAmount(aggregates.totalConsumablesCost, currency), color: [168, 85, 247] },
    { label: 'NET PROFIT (MARGIN)', value: `${formatAmount(aggregates.totalProfit, currency)} (${overallMargin}%)`, color: aggregates.totalProfit >= 0 ? [16, 185, 129] : [239, 68, 68] },
  ];

  kpiItems.forEach((kpi) => {
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(startX, kpiY, kpiBoxWidth, 18, 1.5, 1.5, 'F');
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(startX, kpiY, kpiBoxWidth, 18, 1.5, 1.5, 'S');

    // Accent top
    doc.setFillColor(kpi.color[0], kpi.color[1], kpi.color[2]);
    doc.rect(startX, kpiY, kpiBoxWidth, 2, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.text(kpi.label, startX + 3, kpiY + 7);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(15, 23, 42);
    doc.text(kpi.value, startX + 3, kpiY + 14);

    startX += kpiBoxWidth + kpiGap;
  });

  // Table of Job Cards
  const tableRows = jobCards.map((jc) => {
    const pnl = calculatePnl(jc);
    return [
      jc.jobCardNumber,
      jc.jobType.toUpperCase(),
      jc.customerName,
      jc.vehicleDetails || 'N/A',
      formatAmount(pnl.totalRevenue, currency),
      formatAmount(pnl.partsCost, currency),
      formatAmount(pnl.laborCost, currency),
      formatAmount(pnl.consumablesCost, currency),
      formatAmount(pnl.totalJobCost, currency),
      formatAmount(pnl.netProfit, currency),
      `${pnl.profitMargin}%`,
    ];
  });

  autoTable(doc, {
    startY: 60,
    head: [
      [
        'Job #',
        'Type',
        'Customer',
        'Vehicle',
        'Revenue',
        'Parts Cost',
        'Labor Cost',
        'Consumables',
        'Total Cost',
        'Net Profit',
        'Margin %',
      ],
    ],
    body: tableRows,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 41, 59],
      textColor: [255, 255, 255],
      fontSize: 8,
      fontStyle: 'bold',
      halign: 'center',
    },
    columnStyles: {
      0: { cellWidth: 26, fontStyle: 'bold' },
      1: { cellWidth: 16, halign: 'center' },
      2: { cellWidth: 38 },
      3: { cellWidth: 42 },
      4: { cellWidth: 23, halign: 'right' },
      5: { cellWidth: 22, halign: 'right' },
      6: { cellWidth: 22, halign: 'right' },
      7: { cellWidth: 22, halign: 'right' },
      8: { cellWidth: 23, halign: 'right' },
      9: { cellWidth: 23, halign: 'right', fontStyle: 'bold' },
      10: { cellWidth: 18, halign: 'center' },
    },
    styles: {
      fontSize: 7.5,
      cellPadding: 2.2,
      textColor: [51, 65, 85],
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
  });

  // Footer
  drawPdfFooter(doc);

  // Download
  doc.save(`Workshop_JobCard_PnL_Report_${today}.pdf`);
};

// ─────────────────────────────────────────────────────────────────────────────
// 3. SINGLE JOB CARD ITEMIZED P&L SHEET PDF EXPORTER
// ─────────────────────────────────────────────────────────────────────────────
export const exportSingleJobCardPnlPDF = (
  jc: JobCard,
  pnl: JobCardPnlBreakdown,
  settings?: Partial<SystemSettings>
) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const currency = settings?.currency || 'OMR';

  // Header
  drawPdfHeader(
    doc,
    'JOB CARD P&L STATEMENT',
    `Vehicle: ${jc.vehicleDetails || 'Standard Vehicle'}`,
    `#${jc.jobCardNumber}`,
    settings
  );

  // Metadata Card
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, 35, 182, 24, 2, 2, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, 35, 182, 24, 2, 2, 'S');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text('CUSTOMER & VEHICLE RECONCILIATION:', 18, 41);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(15, 23, 42);
  doc.text(`Customer: ${jc.customerName} (${jc.contactPhone || 'N/A'})`, 18, 47);
  doc.text(`Vehicle: ${jc.vehicleDetails || 'Vehicle'} • Plate: ${jc.plateNumber || 'N/A'} • VIN: ${jc.vinNumber || 'N/A'}`, 18, 53);

  doc.text(`Job Type: ${jc.jobType.toUpperCase()} Service`, 120, 47);
  doc.text(`Status: ${jc.status.replace(/_/g, ' ').toUpperCase()}`, 120, 53);

  let currentY = 64;

  // 1. Parts Table
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(30, 41, 59);
  doc.text('1. Spare Parts Allocated & Requisitioned (g.1)', 14, currentY);

  const partsRows = (jc.partsRequired || []).map((p, i) => [
    (i + 1).toString(),
    p.partNumber,
    p.partName,
    p.quantity.toString(),
    formatAmount(p.unitCost, currency),
    formatAmount(p.quantity * p.unitCost, currency),
    formatAmount(p.quantity * p.unitPrice, currency),
  ]);

  autoTable(doc, {
    startY: currentY + 3,
    head: [['#', 'Part #', 'Item Name', 'Qty', 'Unit Cost', 'Total Cost', 'Billed Revenue']],
    body: partsRows.length > 0 ? partsRows : [['-', '-', 'No spare parts allocated', '0', '0.000', '0.000', '0.000']],
    theme: 'grid',
    headStyles: { fillColor: [79, 70, 229], fontSize: 8, textColor: [255, 255, 255] },
    styles: { fontSize: 7.5, cellPadding: 2 },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 28 },
      2: { cellWidth: 'auto' },
      3: { cellWidth: 14, halign: 'center' },
      4: { cellWidth: 25, halign: 'right' },
      5: { cellWidth: 28, halign: 'right' },
      6: { cellWidth: 28, halign: 'right' },
    },
  });

  currentY = (doc as any).lastAutoTable.finalY + 8;

  // 2. Labor Table
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(30, 41, 59);
  doc.text('2. Technician Labor Time & Direct Wage Costs (g.2)', 14, currentY);

  const laborRows = (jc.laborEntries || []).map((l, i) => [
    (i + 1).toString(),
    l.technicianName,
    l.operation,
    `${l.hours} hrs`,
    formatAmount(l.hourlyWageCost, currency),
    formatAmount(l.hours * l.hourlyWageCost, currency),
    formatAmount(l.hours * l.hourlyChargeRate, currency),
  ]);

  autoTable(doc, {
    startY: currentY + 3,
    head: [['#', 'Technician', 'Operation', 'Hours', 'Wage Cost/hr', 'Total Wage Cost', 'Billed Labor']],
    body: laborRows.length > 0 ? laborRows : [['-', 'General Tech', 'Standard Check', '1 hr', '5.000', '5.000', '15.000']],
    theme: 'grid',
    headStyles: { fillColor: [217, 119, 6], fontSize: 8, textColor: [255, 255, 255] },
    styles: { fontSize: 7.5, cellPadding: 2 },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 32 },
      2: { cellWidth: 'auto' },
      3: { cellWidth: 18, halign: 'center' },
      4: { cellWidth: 25, halign: 'right' },
      5: { cellWidth: 28, halign: 'right' },
      6: { cellWidth: 28, halign: 'right' },
    },
  });

  currentY = (doc as any).lastAutoTable.finalY + 8;

  // Final P&L Statement Box (g.3)
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, currentY, 182, 38, 2, 2, 'F');
  doc.setDrawColor(203, 213, 225);
  doc.roundedRect(14, currentY, 182, 38, 2, 2, 'S');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(30, 41, 59);
  doc.text('3. Job Card Profit & Loss Summary (g.3)', 18, currentY + 6);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);

  // Column 1
  doc.text(`Total Quoted Revenue: ${formatAmount(pnl.totalRevenue, currency)}`, 18, currentY + 14);
  doc.text(`Spare Parts Direct Cost: ${formatAmount(pnl.partsCost, currency)}`, 18, currentY + 20);
  doc.text(`Technician Labor Wage: ${formatAmount(pnl.laborCost, currency)}`, 18, currentY + 26);
  doc.text(`Consumables Allocated: ${formatAmount(pnl.consumablesCost, currency)}`, 18, currentY + 32);

  // Column 2 - Highlighting Gross Profit & Margin
  doc.setFillColor(pnl.netProfit >= 0 ? 16 : 239, pnl.netProfit >= 0 ? 185 : 68, pnl.netProfit >= 0 ? 129 : 68);
  doc.roundedRect(115, currentY + 10, 75, 22, 1.5, 1.5, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(255, 255, 255);
  doc.text('NET JOB PROFIT:', 120, currentY + 17);
  doc.setFontSize(11);
  doc.text(`${formatAmount(pnl.netProfit, currency)}`, 120, currentY + 23);
  doc.setFontSize(8);
  doc.text(`Gross Margin: ${pnl.profitMargin}% • Cost: ${formatAmount(pnl.totalJobCost, currency)}`, 120, currentY + 29);

  drawPdfFooter(doc);

  doc.save(`PnL_JobCard_${jc.jobCardNumber}.pdf`);
};

// ─────────────────────────────────────────────────────────────────────────────
// 4. ENTERPRISE FINANCIAL PROFIT & LOSS STATEMENT PDF EXPORTER
// ─────────────────────────────────────────────────────────────────────────────
export const exportFinancePnlStatementPDF = (
  pnl: {
    grossSales: number;
    estimatedCogs: number;
    grossProfit: number;
    opex: number;
    netOperatingIncome: number;
  },
  currency: string = 'OMR',
  settings?: Partial<SystemSettings>
) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const today = new Date().toISOString().split('T')[0];

  drawPdfHeader(
    doc,
    'INCOME STATEMENT (P&L)',
    `Fiscal Period: Q1-Q4 ${new Date().getFullYear()}`,
    `AUDITED FINANCIALS`,
    settings
  );

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text('STATEMENT OF COMPREHENSIVE PROFIT & LOSS', 14, 38);

  const grossMarginPct =
    pnl.grossSales > 0 ? ((pnl.grossProfit / pnl.grossSales) * 100).toFixed(1) : '0.0';
  const netMarginPct =
    pnl.grossSales > 0 ? ((pnl.netOperatingIncome / pnl.grossSales) * 100).toFixed(1) : '0.0';

  const rows = [
    ['1. REVENUE & TURNOVER', '', ''],
    ['   Gross Workshop & Merchandise Revenue', formatAmount(pnl.grossSales, currency), '100.0%'],
    ['   Less: Sales Discounts & Allowances', formatAmount(0, currency), '0.0%'],
    ['   NET REVENUE', formatAmount(pnl.grossSales, currency), '100.0%'],
    ['', '', ''],
    ['2. COST OF SALES & PRODUCTION (COGS)', '', ''],
    ['   Direct Spare Parts Cost', formatAmount(pnl.estimatedCogs * 0.65, currency), '31.2%'],
    ['   Direct Workshop Technician Labor', formatAmount(pnl.estimatedCogs * 0.25, currency), '12.0%'],
    ['   Shop Consumables, Materials & Freight', formatAmount(pnl.estimatedCogs * 0.1, currency), '4.8%'],
    ['   TOTAL COST OF SALES (COGS)', `(${formatAmount(pnl.estimatedCogs, currency)})`, '48.0%'],
    ['', '', ''],
    ['3. GROSS OPERATING PROFIT', formatAmount(pnl.grossProfit, currency), `${grossMarginPct}%`],
    ['', '', ''],
    ['4. OPERATING EXPENSES (OPEX)', '', ''],
    ['   Rent, Utilities & Facility Overheads', formatAmount(pnl.opex * 0.45, currency), ''],
    ['   Administrative & Supervisory Payroll', formatAmount(pnl.opex * 0.35, currency), ''],
    ['   Equipment Depreciation & Maintenance', formatAmount(pnl.opex * 0.12, currency), ''],
    ['   General & Office Miscellaneous', formatAmount(pnl.opex * 0.08, currency), ''],
    ['   TOTAL OPERATING EXPENSES', `(${formatAmount(pnl.opex, currency)})`, ''],
    ['', '', ''],
    ['5. NET OPERATING PROFIT (EBITDA)', formatAmount(pnl.netOperatingIncome, currency), `${netMarginPct}%`],
  ];

  autoTable(doc, {
    startY: 42,
    head: [['Financial Line Item Description', 'Amount', '% of Revenue']],
    body: rows,
    theme: 'plain',
    headStyles: {
      fillColor: [30, 41, 59],
      textColor: [255, 255, 255],
      fontSize: 9,
      fontStyle: 'bold',
    },
    styles: {
      fontSize: 8.5,
      cellPadding: 2.2,
      textColor: [30, 41, 59],
    },
    columnStyles: {
      0: { cellWidth: 120 },
      1: { cellWidth: 42, halign: 'right', fontStyle: 'bold' },
      2: { cellWidth: 20, halign: 'right' },
    },
    didParseCell: (data) => {
      // Highlight total and header rows
      const text = data.cell.raw as string;
      if (
        text.startsWith('1.') ||
        text.startsWith('2.') ||
        text.startsWith('4.')
      ) {
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.textColor = [67, 56, 202]; // Indigo 700
      } else if (
        text.includes('GROSS OPERATING PROFIT') ||
        text.includes('NET OPERATING PROFIT') ||
        text.includes('NET REVENUE')
      ) {
        data.cell.styles.fontStyle = 'bold';
        data.cell.styles.fillColor = [241, 245, 249];
        data.cell.styles.textColor = [15, 23, 42];
      }
    },
  });

  drawPdfFooter(doc);

  doc.save(`Financial_Income_Statement_PnL_${today}.pdf`);
};

// ─────────────────────────────────────────────────────────────────────────────
// 5. VEHICLE ESTIMATE & QUOTATION PDF EXPORTER
// ─────────────────────────────────────────────────────────────────────────────
export const exportEstimateQuotationPDF = (
  estimate: Estimate,
  settings?: Partial<SystemSettings>
) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const currency = settings?.currency || 'OMR';

  drawPdfHeader(
    doc,
    'VEHICLE REPAIR ESTIMATE',
    `Date: ${estimate.date}`,
    estimate.estimateNumber,
    settings
  );

  // Customer & Vehicle Card
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, 35, 182, 28, 2, 2, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, 35, 182, 28, 2, 2, 'S');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text('CLIENT & VEHICLE DETAILS:', 18, 41);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(15, 23, 42);
  doc.text(`Customer Name: ${estimate.customerName}`, 18, 47);
  doc.text(`Phone: ${estimate.contactPhone || 'N/A'}`, 18, 52);
  doc.text(`Vehicle: ${estimate.vehicleDetails || 'Standard'} • Policy: ${estimate.policyNumber || 'N/A'}`, 18, 57);

  doc.text(`Estimate Type: ${estimate.estimateType === 'parts_labour' ? 'Detailed (Parts + Labour)' : 'Lump-sum Package'}`, 112, 47);
  doc.text(`Quotation Status: ${estimate.status.toUpperCase()}`, 112, 52);
  doc.text(`Linked Job Card: #${estimate.jobCardNumber || 'Unlinked'}`, 112, 57);

  // Items Table
  const tableRows = (estimate.items || []).map((item, idx) => [
    (idx + 1).toString(),
    item.type.toUpperCase(),
    item.description,
    item.quantity.toString(),
    formatAmount(item.unitPrice, currency),
    formatAmount(item.total, currency),
  ]);

  autoTable(doc, {
    startY: 68,
    head: [['#', 'Category', 'Description / Service Operation', 'Qty', 'Unit Rate', 'Amount']],
    body: tableRows,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 41, 59],
      textColor: [255, 255, 255],
      fontSize: 8.5,
      fontStyle: 'bold',
    },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 24, halign: 'center' },
      2: { cellWidth: 'auto' },
      3: { cellWidth: 16, halign: 'center' },
      4: { cellWidth: 30, halign: 'right' },
      5: { cellWidth: 30, halign: 'right' },
    },
    styles: {
      fontSize: 8,
      cellPadding: 2.8,
      textColor: [51, 65, 85],
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
  });

  const finalY = (doc as any).lastAutoTable.finalY || 160;

  // Financial Breakdown Box
  const summaryBoxWidth = 80;
  const summaryX = 196 - summaryBoxWidth;
  const currentY = finalY + 8;

  doc.setFillColor(248, 250, 252);
  doc.roundedRect(summaryX, currentY, summaryBoxWidth, 32, 2, 2, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(summaryX, currentY, summaryBoxWidth, 32, 2, 2, 'S');

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(71, 85, 105);
  doc.text('Subtotal (Parts & Labour):', summaryX + 4, currentY + 7);
  doc.text(formatAmount(estimate.subtotal, currency), 192, currentY + 7, { align: 'right' });

  doc.text('VAT / Tax (5%):', summaryX + 4, currentY + 14);
  doc.text(formatAmount(estimate.vatAmount, currency), 192, currentY + 14, { align: 'right' });

  doc.setFillColor(16, 185, 129); // Emerald
  doc.roundedRect(summaryX + 2, currentY + 19, summaryBoxWidth - 4, 10, 1.5, 1.5, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);
  doc.setTextColor(255, 255, 255);
  doc.text('ESTIMATED TOTAL:', summaryX + 5, currentY + 25.5);
  doc.text(formatAmount(estimate.totalAmount, currency), 191, currentY + 25.5, { align: 'right' });

  // Terms & Conditions
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(15, 23, 42);
  doc.text('ESTIMATE TERMS & CONDITIONS:', 14, finalY + 10);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text('1. Validity: This estimate is valid for 15 days from the issue date.', 14, finalY + 16);
  doc.text('2. Additional Work: Any concealed internal damage found upon dismantling will be quoted separately.', 14, finalY + 20);
  doc.text('3. Warranty: Original OEM replacement parts carry 6 months manufacturer warranty.', 14, finalY + 24);
  doc.text('4. Approval: Please sign or reply via WhatsApp to authorize commencement of repair.', 14, finalY + 28);

  drawPdfFooter(doc);

  doc.save(`Estimate_${estimate.estimateNumber}.pdf`);
};

// ─────────────────────────────────────────────────────────────────────────────
// 6. GENERAL LEDGER TRANSACTIONS PDF EXPORTER
// ─────────────────────────────────────────────────────────────────────────────
export const exportGeneralLedgerPDF = (
  transactions: Transaction[],
  currency: string = 'OMR',
  settings?: Partial<SystemSettings>
) => {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  const today = new Date().toISOString().split('T')[0];

  drawPdfHeader(
    doc,
    'GENERAL LEDGER AUDIT TRAIL',
    `Generated: ${today}`,
    `${transactions.length} TRANSACTIONS`,
    settings
  );

  const tableRows = transactions.map((t) => {
    const isExpense = t.type === 'expense';
    return [
      t.id,
      t.date,
      t.referenceNumber,
      t.type.toUpperCase(),
      t.category,
      t.description,
      t.account,
      isExpense ? formatAmount(t.amount, currency) : '0.000',
      !isExpense ? formatAmount(t.amount, currency) : '0.000',
      'CLEARED',
    ];
  });

  autoTable(doc, {
    startY: 36,
    head: [
      [
        'ID',
        'Date',
        'Reference #',
        'Type',
        'Category',
        'Description',
        'Account',
        'Debit (Exp)',
        'Credit (Inc)',
        'Status',
      ],
    ],
    body: tableRows,
    theme: 'grid',
    headStyles: {
      fillColor: [30, 41, 59],
      textColor: [255, 255, 255],
      fontSize: 8,
      fontStyle: 'bold',
      halign: 'center',
    },
    columnStyles: {
      0: { cellWidth: 20 },
      1: { cellWidth: 22 },
      2: { cellWidth: 28 },
      3: { cellWidth: 18, halign: 'center' },
      4: { cellWidth: 28 },
      5: { cellWidth: 'auto' },
      6: { cellWidth: 30 },
      7: { cellWidth: 24, halign: 'right' },
      8: { cellWidth: 24, halign: 'right' },
      9: { cellWidth: 18, halign: 'center' },
    },
    styles: {
      fontSize: 7.5,
      cellPadding: 2,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
  });

  drawPdfFooter(doc);

  doc.save(`General_Ledger_${today}.pdf`);
};
